version: '3.8'

services:
  date-generator:
    build: .
    ports:
      - "${PORT:-7860}:7860"
    volumes:
      - ./app.py:/app/app.py
      - ./custom.css:/app/custom.css
      - ./utilities:/app/utilities
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=${PORT:-7860}
    restart: unless-stopped 