version: '3.8'

services:
  date-generator:
    build: .
    ports:
      - "${PORT:-7860}:7860"
    volumes:
      - ./app.py:/app/app.py
      - ./custom.css:/app/custom.css
      - ./utilities:/app/utilities
      - ./static:/app/static
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - PORT=${PORT:-7860}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 